### ISSUE TITLE
Some Directories missed

### ISSUE THREAD

**Issue by mojtabaSefidi** [cufeinfor/MIRRec#1]
Hi. I tried to run your replication package, but it seems that all the required directories are not uploaded. For instance to run the following lines we need to access `config`, `scikit`, and `utils` directories but they are not available in your repository

```
from source.config.projectConfig import projectConfig
from source.scikit.service.DataProcessUtils import DataProcessUtils
from source.utils.pandas.pandasHelper import pandasHelper
```

**Comment by cufeinfor** [comment]
Regarding the missing directories (config, utils, and scikit) in the MIRRec package, I’ve now uploaded these components. Not all functions within these packages are essential, which is why I initially left them out. You can either modify the relevant paths to use these packages or ignore them entirely, reading with local data paths or using pandas functions directly to achieve the same results.
